version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: kneegorilla
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"

  
  api:
    build: .
    environment:
      - HOST="0.0.0.0"
      - PORT="8080"
    ports:
      - "8080:8080"
    volumes:
      - '.:/go/src/github.com/yumuranaoki/blog-service-by-go'
    command: go run main.go

volumes:
  db_data: